services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - apps_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SenhaAdmin123!
      MYSQL_DATABASE: users_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - apps_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pSenhaAdmin123!"]
      interval: 5s
      timeout: 5s
      retries: 10

  notifications-worker:
    image: splinterxsr/notificationsworker:latest
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_HOST: rabbitmq
      USER_QUEUE_NAME: users-queue
      PAYMENT_QUEUE_NAME: payments-queue
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - apps_network

volumes:
  rabbitmq_data:
  mysql_data:

networks:
  apps_network:
    driver: bridge