apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-api
  labels:
    app: user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.36
          command: 
            - 'sh'
            - '-c'
            - 'until nc -z -w 2 mysql 3306; do echo "aguardando o mysql responder na porta..."; sleep 2; done; echo "Porta aberta! Aguardando 10 segundos para o servidor estabilizar..."; sleep 10;'
      containers:
        - name: user-api
          image: anafmel/usersapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:       
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: user-api-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: AWS_ENDPOINT
              value: "http://localstack:4566"
            - name: AWS_ACCESS_KEY_ID
              value: "test"
            - name: AWS_SECRET_ACCESS_KEY
              value: "test"
            - name: AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  name: user-api-config
                  key: AWS_DEFAULT_REGION
            - name: ConnectionStrings__DefaultConnection
              value: "Server=mysql;Database=users_db;Uid=root;Pwd=SenhaAdmin123!;"
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-api-config
                  key: MYSQL_HOST
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: user-api-mysql-secrets
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: user-api-mysql-secrets
                  key: MYSQL_USER
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-api-mysql-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: JWT_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: JWT_ISSUER
            - name: JWT_SECONDS
              valueFrom:
                configMapKeyRef:
                  name: user-api-config
                  key: JWT_SECONDS
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_KEY

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"  
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: user-api
spec:
  type: ClusterIP
  selector:
    app: user-api
  ports:
    - port: 8080
      targetPort: 8080