apiVersion: v1
kind: Secret
metadata:
  name: users-api-mysql-secrets
type: Opaque
stringData:
  MYSQL_USER: root             
  MYSQL_ROOT_PASSWORD: SenhaAdmin123! 
  MYSQL_DATABASE: users_db
  JWT_SECONDS: "3600"